# =============================================
# Reusable Fields and Fieldsets
# =============================================

textFields:
  - &TEXTFIELD { label: Text, name: text, widget: richtext }

blockSettingsFields:
  - &WIDTHFIELD { label: 'Width (%)', name: width, widget: number, default: 50, step: 5, min: 25, max: 75 }
  - &LEFTORRIGHT { label: Side, name: side, widget: select, default: 'left', options: [{ label: 'Left', value: 'left'}, { label: 'Right', value: 'right'}] }
  - &PADDINGLEVEL { label: 'Padding Level', name: padding, widget: number, default: 0, step: 1, min: 0, max: 10, hint: "Amount of space above and below the text"}

imageFields: &IMAGEFIELDS
  - &IMAGESOURCEFIELD { label: Image, name: image, widget: image, required: false }
  - &IMAGEDESCRIPTIONFIELD { label: Image Description, name: alt, widget: string, required: false }

flexible: &FLEXIBLE
  - label: 'Text Block'
    name: 'text_block'
    widget: object
    fields:
      - *TEXTFIELD
  - label: 'Image'
    name: 'image'
    widget: object
    fields: *IMAGEFIELDS
  - label: 'Two Column Text'
    name: 'two_column_text'
    widget: 'object'
    fields:
      - label: 'Left Block'
        name: 'left_block'
        widget: object
        fields:
          - *TEXTFIELD
          - *WIDTHFIELD
      - label: 'Right Block'
        name: 'right_block'
        widget: object
        fields:
          - *TEXTFIELD
  - label: 'Image and Text'
    name: 'image_and_text'
    widget: 'object'
    fields:
      - label: 'Text'
        name: 'text_block'
        widget: object
        fields:
          - *TEXTFIELD
          - *WIDTHFIELD
          - *PADDINGLEVEL
          - *LEFTORRIGHT
      - label: 'Image'
        name: 'image_block'
        widget: object
        fields: *IMAGEFIELDS
  - label: 'Video'
    name: 'video'
    widget: object
    fields:
      - label: 'Video'
        name: 'video'
        widget: relation
        collection: 'Videos'
        search_fields: ['title']
        display_fields: ['title']
        value_field: '{{slug}}'
        multiple: false
        hint: 'Select a single video to display'
  - label: 'Video Gallery'
    name: 'video_gallery'
    widget: object
    fields:
      - label: "Gallery Type"
        name: "gallery_type"
        widget: "select"
        default: "all"
        options:
          - { label: "Display All Videos", value: "all" }
          - { label: "Select Videos", value: "select" }
      - label: 'Videos'
        name: 'videos'
        widget: relation
        collection: 'Videos'
        search_fields: ['title']
        display_fields: ['title']
        value_field: '{{slug}}'
        multiple: true
        hint: 'Select a list of videos, only works if "Select Videos" is chosen'
        required: false

# =============================================
# Site Config
# =============================================

backend:
  name: git-gateway
  repo: alexrichardsweb/portfolio
  branch: master # Branch to update (optional; defaults to master)
  local_backend: true
#publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
media_library:
  name: uploadcare
  config:
    publicKey: fa4b08df31e2b7a6108e
  settings:
    autoFilename: true
    defaultOperations: '/resize/1600x/'
    imagesOnly: true
    tabs: 'file url facebook'
public_folder: "images/uploads"
collections:
  - name: 'Settings'
    label: 'Site Settings'
    folder: 'content/settings'
    format: 'frontmatter'
    slug: 'settings'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Site Settings Name', name: 'site_settings_name', widget: 'string', default: 'Site Settings' }
      - { label: 'Site Name', name: 'site_name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image', required: false }
      - label: 'Social'
        name: 'social'
        widget: list
        fields:
          - label: 'Social Media'
            name: 'social_media'
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
  - name: 'Backgrounds'
    label: 'Desktop Backgrounds'
    folder: 'content/backgrounds'
    format: 'frontmatter'
    slug: 'backgrounds'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Background Section', name: 'background_section', widget: 'string' }
      - label: 'Backgrounds'
        name: 'background_list'
        widget: list
  - name: 'Menu Items'
    label: 'Menu Item'
    folder: 'content/menu'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', required: false }
      - { label: 'Icon', name: 'icon', widget: 'string', required: false }
      - { label: 'Has Desktop Icon', name: 'has_desktop_icon', widget: 'boolean', required: false, default: true }
      - label: 'Parent'
        name: 'parent'
        widget: 'relation'
        required: false
        collection: 'Menu Items'
        value_field: 'slug'
        search_fields: ['title', 'slug']
        display_fields: ['title']
      - label: 'Window Options'
        name: 'window'
        widget: object
        fields:
          - { label: 'Width', name: 'width', widget: 'number', default: '400', required: false }
          - { label: 'Height', name: 'height', widget: 'number', default: '400', required: false }
          - { label: 'Resizable', name: 'boolean', widget: 'boolean', default: true }
